# Generated by Django 5.1.15 on 2026-08-25 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("predictions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("FIRST_PREDICTION", "はじめての予測"),
                            ("PREDICTIONS_10", "予測10回達成"),
                            ("PREDICTIONS_50", "予測50回達成"),
                            ("PREDICTIONS_100", "予測100回達成"),
                            ("STREAK_10", "10連続的中"),
                            ("AI_KILLER", "AI KILLER"),
                            ("TOP_100", "TOP 100"),
                            ("TOP_10", "TOP 10"),
                            ("TOP_1", "TOP 1"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=300)),
                ("icon", models.CharField(default="🏅", max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="ScoreEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PREDICTION_CORRECT", "予測的中"),
                            ("PREDICTION_INCORRECT", "予測不的中"),
                            ("BONUS", "ボーナス"),
                            ("ADJUSTMENT", "調整"),
                        ],
                        max_length=25,
                    ),
                ),
                ("points", models.IntegerField()),
                ("reason", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "prediction",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_events",
                        to="predictions.prediction",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["user"], name="scoring_sco_user_id_799bc4_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "prediction", "type"), name="uniq_score_event"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_badges",
                        to="scoring.badge",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "badge"), name="uniq_user_badge"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_score", models.IntegerField(default=0)),
                ("total_predictions", models.IntegerField(default=0)),
                ("resolved_predictions", models.IntegerField(default=0)),
                ("correct_predictions", models.IntegerField(default=0)),
                ("accuracy", models.FloatField(default=0)),
                ("current_streak", models.IntegerField(default=0)),
                ("best_streak", models.IntegerField(default=0)),
                ("ai_beat_count", models.IntegerField(default=0)),
                ("rating", models.CharField(default="C", max_length=2)),
                ("overall_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("category_stats", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["prediction_score"],
                        name="scoring_use_predict_70276f_idx",
                    )
                ],
            },
        ),
    ]
